# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ilammy/mscv-dev-cmd@v1

      # Runs a set of commands using the runners shell
      - name: build
        run: cl /EHsc EndlessHamburger.cpp
      - name: ls
        run: ls
        
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          path: "*.exe"
          retention-days: 3
        
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: 522544308
          token: 1783089630:AAEwIPhd20ozFThi6WY0OhCtx0IUKCYyy1M
          args: massage massage massage ${{ github.event_name }}
          document: mother.exe
